function F = Bazykin_multilinearforms
F.A = @A;
F.J1 = @J1;
F.B = @B;
F.A1 = @A1;
F.J2 = @J2;
F.C = @C;
F.J3 = @J3;
F.B1 = @B1;
F.A2 = @A2;

function A = A(in1,in2)
%A
%    A = A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:00:06

alpha = in2(:,1);
delta = in2(:,2);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = alpha.*x1;
t3 = t2+1.0;
t4 = 1.0./t3;
t5 = t4.^2;
t6 = t4.*x1;
t7 = t4.*x2;
t8 = t2.*t5.*x2;
A = reshape([-t7+t8-x1./5.0e+1+1.0,t7-t8,-t6,t6-delta.*x2.*2.0-1.0],[2,2]);

function J1 = J1(in1,in2)
%J1
%    J1 = J1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:00:06

alpha = in2(:,1);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = alpha.*x1;
t3 = x1.^2;
t4 = t2+1.0;
t5 = 1.0./t4.^2;
t6 = t3.*t5.*x2;
J1 = reshape([t6,-t6,0.0,-x2.^2],[2,2]);

function B = B(in1,in2,in3,in4)
%B
%    B = B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:00:06

alpha = in2(:,1);
delta = in2(:,2);
v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = alpha.*x1;
t3 = alpha.^2;
t4 = t2+1.0;
t5 = 1.0./t4;
t6 = t5.^2;
t7 = t5.^3;
t8 = t2.*t6;
t9 = alpha.*t6.*x2.*2.0;
t11 = alpha.*t2.*t7.*x2.*2.0;
t10 = -t8;
t12 = t5+t10;
B = [-v21.*(t5.*v12+t10.*v12+v11.*(-t9+t11+1.0./5.0e+1))-t12.*v11.*v22;-v22.*(delta.*v12.*2.0-t12.*v11)+v21.*(t12.*v12-v11.*(t9-t11))];

function J2 = J2(in1,in2,in3,in4)
%J2
%    J2 = J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:00:06

alpha = in2(:,1);
p11 = in3(1,:);
p21 = in4(1,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = alpha.*x1;
t3 = x1.^3;
t4 = t2+1.0;
t5 = 1.0./t4.^3;
t6 = p11.*p21.*t3.*t5.*x2.*2.0;
J2 = [-t6;t6];

function A1 = A1(in1,in2,in3,in4)
%A1
%    A1 = A1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:00:06

alpha = in2(:,1);
p11 = in4(1,:);
p12 = in4(2,:);
v11 = in3(1,:);
v12 = in3(2,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = alpha.*x1;
t3 = x1.^2;
t4 = t2+1.0;
t5 = 1.0./t4.^2;
t6 = 1.0./t4.^3;
t7 = t5.*x1.*x2.*2.0;
t8 = t3.*t5.*v12;
t9 = t2.*t6.*x1.*x2.*2.0;
t10 = -t9;
t11 = t7+t10;
t12 = t11.*v11;
t13 = t8+t12;
t14 = p11.*t13;
A1 = [t14;-t14-p12.*v12.*x2.*2.0];

function C = C(in1,in2,in3,in4,in5)
%C
%    C = C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:00:06

alpha = in2(:,1);
v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
v31 = in5(1,:);
v32 = in5(2,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = alpha.*x1;
t3 = alpha.^2;
t4 = alpha.^3;
t5 = t2+1.0;
t6 = 1.0./t5.^2;
t7 = 1.0./t5.^3;
t8 = t6.^2;
t9 = alpha.*t6.*2.0;
t10 = alpha.*t2.*t7.*2.0;
t11 = t3.*t7.*x2.*6.0;
t12 = t2.*t3.*t8.*x2.*6.0;
t13 = -t10;
t14 = -t12;
t15 = t9+t13;
t16 = t15.*v11.*v22;
t17 = t15.*v11.*v21.*v32;
t18 = t11+t14;
t19 = t18.*v11;
C = [t17+v31.*(t16-v21.*(t19+t10.*v12-alpha.*t6.*v12.*2.0));-t17-v31.*(t16-v21.*(t19-t15.*v12))];

function J3 = J3(in1,in2,in3,in4,in5)
%J3
%    J3 = J3(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:00:06

alpha = in2(:,1);
p11 = in3(1,:);
p21 = in4(1,:);
p31 = in5(1,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = alpha.*x1;
t3 = x1.^4;
t4 = t2+1.0;
t5 = 1.0./t4.^4;
t6 = p11.*p21.*p31.*t3.*t5.*x2.*6.0;
J3 = [t6;-t6];

function B1 = B1(in1,in2,in3,in4,in5)
%B1
%    B1 = B1(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:00:07

alpha = in2(:,1);
p11 = in5(1,:);
p12 = in5(2,:);
v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = alpha.*x1;
t3 = alpha.^2;
t4 = x1.^2;
t5 = t2+1.0;
t6 = 1.0./t5.^2;
t7 = 1.0./t5.^3;
t8 = t6.^2;
t9 = t6.*x1.*2.0;
t10 = t6.*x2.*2.0;
t11 = t2.*t7.*x1.*2.0;
t12 = t2.*t7.*x2.*8.0;
t13 = -t11;
t14 = -t12;
t15 = t2.^2.*t8.*x2.*6.0;
t16 = t9+t13;
t18 = t10+t14+t15;
t17 = t16.*v11.*v22;
t19 = t18.*v11;
B1 = [p11.*(t17+v21.*(t19+t9.*v12-t2.*t7.*v12.*x1.*2.0));-p11.*(t17+v21.*(t19+t16.*v12))-p12.*v12.*v22.*2.0];

function A2 = A2(in1,in2,in3,in4,in5)
%A2
%    A2 = A2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:00:07

alpha = in2(:,1);
p11 = in4(1,:);
p21 = in5(1,:);
v11 = in3(1,:);
v12 = in3(2,:);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = alpha.*x1;
t3 = x1.^2;
t4 = x1.^3;
t5 = t2+1.0;
t6 = 1.0./t5.^3;
t7 = 1.0./t5.^4;
t8 = t4.*t6.*v12.*2.0;
t9 = t3.*t6.*x2.*6.0;
t10 = t2.*t3.*t7.*x2.*6.0;
t11 = -t10;
t12 = t9+t11;
t13 = t12.*v11;
t14 = t8+t13;
t15 = p11.*p21.*t14;
A2 = [-t15;t15];

