function F = BogdanovTakensNormalForm_multilinearforms
F.A = @A;
F.J1 = @J1;
F.B = @B;
F.A1 = @A1;
F.J2 = @J2;
F.C = @C;
F.J3 = @J3;
F.B1 = @B1;
F.A2 = @A2;

function A = A(in1,in2)
%A
%    A = A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:14:19

beta2 = in2(:,2);
w0 = in1(:,1);
w1 = in1(:,2);
A = reshape([0.0,w0.*-2.0+w1,1.0,beta2+w0],[2,2]);

function J1 = J1(in1,in2)
%J1
%    J1 = J1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:14:19

w1 = in1(:,2);
J1 = reshape([0.0,1.0,0.0,w1],[2,2]);

function B = B(in1,in2,in3,in4)
%B
%    B = B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:14:19

v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
B = [0.0;v11.*v22-v21.*(v11.*2.0-v12)];

function J2 = J2(in1,in2,in3,in4)
%J2
%    J2 = J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:14:19

J2 = [0.0;0.0];

function A1 = A1(in1,in2,in3,in4)
%A1
%    A1 = A1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:14:19

p12 = in4(2,:);
v12 = in3(2,:);
A1 = [0.0;p12.*v12];

function C = C(in1,in2,in3,in4,in5)
%C
%    C = C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:14:20

C = [0.0;0.0];

function J3 = J3(in1,in2,in3,in4,in5)
%J3
%    J3 = J3(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:14:20

J3 = [0.0;0.0];

function B1 = B1(in1,in2,in3,in4,in5)
%B1
%    B1 = B1(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:14:20

B1 = [0.0;0.0];

function A2 = A2(in1,in2,in3,in4,in5)
%A2
%    A2 = A2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:14:20

A2 = [0.0;0.0];

