function F = CO_oxidation_multilinearforms
F.A = @A;
F.J1 = @J1;
F.B = @B;
F.A1 = @A1;
F.J2 = @J2;
F.C = @C;
F.J3 = @J3;
F.B1 = @B1;
F.A2 = @A2;

function A = A(in1,in2)
%A
%    A = A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:16:19

k1 = in2(:,1);
k2 = in2(:,4);
k3 = in2(:,3);
k4 = in2(:,6);
km1 = in2(:,2);
km2 = in2(:,5);
lambda = in2(:,7);
s = in1(:,3);
x = in1(:,1);
y = in1(:,2);
t2 = k3.*x;
t3 = k3.*y;
t4 = s.*2.0;
t5 = x.*2.0;
t6 = y.*2.0;
t7 = -k2;
t8 = -k4;
t9 = -t2;
t10 = -t3;
t11 = t4+t5+t6-2.0;
t12 = k1.*t11.*2.0;
A = reshape([t10+t12-km1.*x.*4.0,t7+t10,t8,t9+t12,-km2+t7+t9,t8,t12,t7,t8.*(lambda+1.0)],[3,3]);

function J1 = J1(in1,in2)
%J1
%    J1 = J1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:16:20

k4 = in2(:,6);
lambda = in2(:,7);
s = in1(:,3);
x = in1(:,1);
y = in1(:,2);
t2 = x.*y;
t3 = -s;
t4 = -x;
t5 = -y;
t6 = -t2;
J1 = reshape([(s+x+y-1.0).^2.*2.0,0.0,0.0,x.^2.*-2.0,0.0,0.0,t6,t6,0.0,0.0,t3+t4+t5+1.0,0.0,0.0,t5,0.0,0.0,0.0,t3+t4+t5+lambda.*t3+1.0,0.0,0.0,k4.*t3],[3,7]);

function B = B(in1,in2,in3,in4)
%B
%    B = B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:16:20

k1 = in2(:,1);
k3 = in2(:,3);
km1 = in2(:,2);
v11 = in3(1,:);
v12 = in3(2,:);
v13 = in3(3,:);
v21 = in4(1,:);
v22 = in4(2,:);
v23 = in4(3,:);
t2 = k1.*4.0;
t5 = -k3;
t3 = t2.*v12;
t4 = t2.*v13;
t6 = t2+t5;
B = [-v21.*(-t4+v12.*(k3-t2)+v11.*(km1.*4.0-t2))+v23.*(t3+t4+t2.*v11)+v22.*(t3+t4-v11.*(k3-t2));t5.*v11.*v22+t5.*v12.*v21;0.0];

function J2 = J2(in1,in2,in3,in4)
%J2
%    J2 = J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:16:20

p16 = in3(6,:);
p17 = in3(7,:);
p26 = in4(6,:);
p27 = in4(7,:);
s = in1(:,3);
J2 = [0.0;0.0;-p16.*p27.*s-p17.*p26.*s];

function A1 = A1(in1,in2,in3,in4)
%A1
%    A1 = A1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:16:20

k4 = in2(:,6);
lambda = in2(:,7);
p11 = in4(1,:);
p12 = in4(2,:);
p13 = in4(3,:);
p14 = in4(4,:);
p15 = in4(5,:);
p16 = in4(6,:);
p17 = in4(7,:);
s = in1(:,3);
v11 = in3(1,:);
v12 = in3(2,:);
v13 = in3(3,:);
x = in1(:,1);
y = in1(:,2);
t2 = v12.*x;
t3 = v11.*y;
t4 = s.*4.0;
t5 = x.*4.0;
t6 = y.*4.0;
t7 = t2+t3;
t10 = t4+t5+t6-4.0;
t8 = p13.*t7;
t9 = -t8;
A1 = [t9+p11.*(t10.*v11+t10.*v12+v13.*(s.*2.0+x.*2.0+y.*2.0-2.0).*2.0)-p12.*v11.*x.*4.0;t9-p15.*v12-p14.*(v11+v12+v13);-p16.*(v11+v12+v13.*(lambda+1.0))-k4.*p17.*v13];

function C = C(in1,in2,in3,in4,in5)
%C
%    C = C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:16:20

C = [0.0;0.0;0.0];

function J3 = J3(in1,in2,in3,in4,in5)
%J3
%    J3 = J3(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:16:20

J3 = [0.0;0.0;0.0];

function B1 = B1(in1,in2,in3,in4,in5)
%B1
%    B1 = B1(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:16:20

p11 = in5(1,:);
p12 = in5(2,:);
p13 = in5(3,:);
v11 = in3(1,:);
v12 = in3(2,:);
v13 = in3(3,:);
v21 = in4(1,:);
v22 = in4(2,:);
v23 = in4(3,:);
t2 = v11.*v22;
t3 = v12.*v21;
t4 = v11.*4.0;
t5 = v12.*4.0;
t6 = v13.*4.0;
t7 = t2+t3;
t9 = t4+t5+t6;
t8 = p13.*t7;
t10 = -t8;
B1 = [t10+p11.*(t9.*v21+t9.*v22+t9.*v23)-p12.*v11.*v21.*4.0;t10;0.0];

function A2 = A2(in1,in2,in3,in4,in5)
%A2
%    A2 = A2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:16:20

p16 = in4(6,:);
p17 = in4(7,:);
p26 = in5(6,:);
p27 = in5(7,:);
v13 = in3(3,:);
A2 = [0.0;0.0;-p16.*p27.*v13-p17.*p26.*v13];

