function F = extendedLorenz84_multilinearforms
F.A = @A;
F.J1 = @J1;
F.B = @B;
F.A1 = @A1;
F.J2 = @J2;
F.C = @C;
F.J3 = @J3;
F.B1 = @B1;
F.A2 = @A2;

function A = A(in1,in2)
%A
%    A = A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:21:32

U = in1(:,4);
X = in1(:,1);
Y = in1(:,2);
Z = in1(:,3);
t2 = X-1.0;
A = reshape([-1.0./4.0,Y-Z,Y+Z,U.*(9.87e+2./1.0e+3),Y.*-2.0,t2,X,0.0,Z.*-2.0,-X,t2,0.0,U.*(-9.87e+2./5.0e+2),0.0,0.0,X.*(9.87e+2./1.0e+3)-2.6e+1./2.5e+1],[4,4]);

function J1 = J1(in1,in2)
%J1
%    J1 = J1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:21:32

J1 = reshape([1.0./4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[4,2]);

function B = B(in1,in2,in3,in4)
%B
%    B = B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:21:32

v11 = in3(1,:);
v12 = in3(2,:);
v13 = in3(3,:);
v14 = in3(4,:);
v21 = in4(1,:);
v22 = in4(2,:);
v23 = in4(3,:);
v24 = in4(4,:);
t2 = v11.*v22;
t3 = v11.*v23;
B = [v12.*v22.*-2.0-v13.*v23.*2.0-v14.*v24.*(9.87e+2./5.0e+2);t2-t3+v21.*(v12-v13);t2+t3+v21.*(v12+v13);v11.*v24.*(9.87e+2./1.0e+3)+v14.*v21.*(9.87e+2./1.0e+3)];

function J2 = J2(in1,in2,in3,in4)
%J2
%    J2 = J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:21:32

J2 = [0.0;0.0;0.0;0.0];

function A1 = A1(in1,in2,in3,in4)
%A1
%    A1 = A1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:21:32

A1 = [0.0;0.0;0.0;0.0];

function C = C(in1,in2,in3,in4,in5)
%C
%    C = C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:21:32

C = [0.0;0.0;0.0;0.0];

function J3 = J3(in1,in2,in3,in4,in5)
%J3
%    J3 = J3(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:21:32

J3 = [0.0;0.0;0.0;0.0];

function B1 = B1(in1,in2,in3,in4,in5)
%B1
%    B1 = B1(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:21:32

B1 = [0.0;0.0;0.0;0.0];

function A2 = A2(in1,in2,in3,in4,in5)
%A2
%    A2 = A2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:21:32

A2 = [0.0;0.0;0.0;0.0];

