function F = HodgkinHuxley_multilinearforms
F.A = @A;
F.J1 = @J1;
F.B = @B;
F.A1 = @A1;
F.J2 = @J2;
F.C = @C;
F.J3 = @J3;
F.B1 = @B1;
F.A2 = @A2;

function A = A(in1,in2)
%A
%    A = A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:27:42

V = in1(:,1);
VbarK = in2(:,1);
h = in1(:,4);
m = in1(:,2);
n = in1(:,3);
t2 = m.^3;
t3 = m-1.0;
t4 = n-1.0;
t5 = V+1.15e+2;
t6 = V./1.0e+1;
t7 = V./1.8e+1;
t8 = V./2.0e+1;
t11 = V./8.0e+1;
t9 = exp(t7);
t10 = exp(t8);
t12 = t6+1.0;
t14 = exp(t11);
t17 = t6+5.0./2.0;
t13 = t12+2.0;
t15 = exp(t12);
t18 = exp(t17);
t16 = exp(t13);
t20 = t15-1.0;
t21 = t18-1.0;
t19 = t16+1.0;
t22 = 1.0./t20;
t23 = 1.0./t21;
A = reshape([h.*t2.*-1.2e+2-n.^4.*3.6e+1-3.0./1.0e+1,m.*t9.*(-1.0./4.5e+1)-(t3.*t23)./1.0e+2+(t3.*t17.*t18.*t23.^2)./1.0e+2,n.*t14.*(-1.5625e-4)-(t4.*t22)./1.0e+3+(t4.*t12.*t15.*t22.^2)./1.0e+3,t10.*(h-1.0).*(-3.5e-4)+(h.*t16.*1.0./t19.^2)./1.0e+2,h.*m.^2.*t5.*-3.6e+2,t9.*(-2.0./5.0)-(t17.*t23)./1.0e+1,0.0,0.0,n.^3.*(V-VbarK).*-1.44e+2,0.0,t14.*(-1.0./8.0e+1)-(t12.*t22)./1.0e+2,0.0,t2.*t5.*-1.2e+2,0.0,0.0,t10.*(-7.0./1.0e+3)-1.0./(t19.*1.0e+1)],[4,4]);

function J1 = J1(in1,in2)
%J1
%    J1 = J1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:27:42

n = in1(:,3);
J1 = reshape([n.^4.*3.6e+1,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[4,2]);

function B = B(in1,in2,in3,in4)
%B
%    B = B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:27:42

V = in1(:,1);
VbarK = in2(:,1);
h = in1(:,4);
m = in1(:,2);
n = in1(:,3);
v11 = in3(1,:);
v12 = in3(2,:);
v13 = in3(3,:);
v14 = in3(4,:);
v21 = in4(1,:);
v22 = in4(2,:);
v23 = in4(3,:);
v24 = in4(4,:);
t2 = m.^2;
t3 = m.^3;
t4 = n.^3;
t5 = m-1.0;
t6 = n-1.0;
t7 = V./5.0;
t8 = V+1.15e+2;
t9 = V./1.0e+1;
t10 = V./1.8e+1;
t11 = V./2.0e+1;
t14 = V./8.0e+1;
t12 = exp(t10);
t13 = exp(t11);
t15 = t9+1.0;
t17 = exp(t14);
t20 = t9+5.0./2.0;
t16 = t15+2.0;
t18 = exp(t15);
t21 = exp(t20);
t23 = t12./4.5e+1;
t29 = t17./6.4e+3;
t30 = t13.*3.5e-4;
t19 = exp(t16);
t24 = t18-1.0;
t26 = t21-1.0;
t22 = t19+1.0;
t27 = 1.0./t24;
t31 = 1.0./t26;
t25 = 1.0./t22.^2;
t28 = t27.^2;
t32 = t31.^2;
t33 = t27./1.0e+3;
t34 = t31./1.0e+2;
t35 = (t19.*t25)./1.0e+2;
t37 = (t15.*t18.*t28)./1.0e+3;
t39 = (t20.*t21.*t32)./1.0e+2;
t36 = -t35;
t38 = -t37;
t40 = -t39;
t41 = t30+t36;
t42 = t29+t33+t38;
t43 = t23+t34+t40;
B = [-v24.*(t3.*v11.*1.2e+2+t2.*t8.*v12.*3.6e+2)-v21.*(t3.*v14.*1.2e+2+t4.*v13.*1.44e+2+h.*t2.*v12.*3.6e+2)-v23.*(t4.*v11.*1.44e+2+n.^2.*v13.*(V-VbarK).*4.32e+2)-v22.*(h.*t2.*v11.*3.6e+2+t2.*t8.*v14.*3.6e+2+h.*m.*t8.*v12.*7.2e+2);-v21.*(t43.*v12+v11.*((m.*t12)./8.1e+2-(t5.*t21.*t32)./5.0e+2-(t5.*t20.*t21.*t32)./1.0e+3+(t5.*t20.*t31.^3.*exp(t7+5.0))./5.0e+2))-t43.*v11.*v22;-v21.*(t42.*v13+v11.*((n.*t17)./5.12e+5-(t6.*t18.*t28)./5.0e+3-(t6.*t15.*t18.*t28)./1.0e+4+(t6.*t15.*t27.^3.*exp(t7+2.0))./5.0e+3))-t42.*v11.*v23;-v21.*(t41.*v14+v11.*(t13.*(h-1.0).*1.75e-5-(h.*t19.*t25)./1.0e+3+(h.*1.0./t22.^3.*exp(t7+6.0))./5.0e+2))-t41.*v11.*v24];

function J2 = J2(in1,in2,in3,in4)
%J2
%    J2 = J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:27:42

J2 = [0.0;0.0;0.0;0.0];

function A1 = A1(in1,in2,in3,in4)
%A1
%    A1 = A1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:27:42

n = in1(:,3);
p11 = in4(1,:);
v13 = in3(3,:);
A1 = [n.^3.*p11.*v13.*1.44e+2;0.0;0.0;0.0];

function C = C(in1,in2,in3,in4,in5)
%C
%    C = C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:27:43

V = in1(:,1);
VbarK = in2(:,1);
h = in1(:,4);
m = in1(:,2);
n = in1(:,3);
v11 = in3(1,:);
v12 = in3(2,:);
v13 = in3(3,:);
v14 = in3(4,:);
v21 = in4(1,:);
v22 = in4(2,:);
v23 = in4(3,:);
v24 = in4(4,:);
v31 = in5(1,:);
v32 = in5(2,:);
v33 = in5(3,:);
v34 = in5(4,:);
t2 = m.^2;
t3 = n.^2;
t4 = m-1.0;
t5 = n-1.0;
t6 = V./5.0;
t7 = V+1.15e+2;
t8 = V./1.0e+1;
t9 = V./1.8e+1;
t10 = V./2.0e+1;
t16 = V./8.0e+1;
t25 = h.*m.*v12.*7.2e+2;
t11 = t6+2.0;
t14 = exp(t9);
t15 = exp(t10);
t17 = t8+1.0;
t19 = exp(t16);
t23 = t2.*v11.*3.6e+2;
t24 = t2.*v14.*3.6e+2;
t28 = t8+5.0./2.0;
t32 = m.*t7.*v12.*7.2e+2;
t12 = t11+3.0;
t18 = t17+2.0;
t20 = exp(t11);
t26 = exp(t17);
t29 = exp(t28);
t35 = t14./8.1e+2;
t39 = t15.*1.75e-5;
t42 = t19./5.12e+5;
t43 = t24+t25;
t44 = t23+t32;
t13 = t12+1.0;
t21 = exp(t12);
t27 = exp(t18);
t31 = t26-1.0;
t36 = t29-1.0;
t22 = exp(t13);
t30 = t27+1.0;
t37 = 1.0./t31.^2;
t38 = 1.0./t31.^3;
t40 = 1.0./t36.^2;
t41 = 1.0./t36.^3;
t33 = 1.0./t30.^2;
t34 = 1.0./t30.^3;
t48 = (t26.*t37)./5.0e+3;
t50 = (t29.*t40)./5.0e+2;
t52 = (t17.*t20.*t38)./5.0e+3;
t53 = (t17.*t26.*t37)./1.0e+4;
t54 = (t21.*t28.*t41)./5.0e+2;
t56 = (t28.*t29.*t40)./1.0e+3;
t45 = (t22.*t34)./5.0e+2;
t46 = (t27.*t33)./1.0e+3;
t49 = -t48;
t51 = -t50;
t55 = -t53;
t57 = -t56;
t47 = -t46;
t59 = t42+t49+t52+t55;
t60 = t35+t51+t54+t57;
t58 = t39+t45+t47;
C = [-v32.*(v22.*(h.*m.*v11.*7.2e+2+h.*t7.*v12.*7.2e+2+m.*t7.*v14.*7.2e+2)+t43.*v21+t44.*v24)-v33.*(v23.*(t3.*v11.*4.32e+2+n.*v13.*(V-VbarK).*8.64e+2)+t3.*v13.*v21.*4.32e+2)-v34.*(t44.*v22+t2.*v12.*v21.*3.6e+2)-v31.*(t43.*v22+t2.*v12.*v24.*3.6e+2+t3.*v13.*v23.*4.32e+2);-v31.*(v21.*(t60.*v12+v11.*((m.*t14)./1.458e+4+t4.*t21.*t41.*6.0e-4-t4.*t29.*t40.*3.0e-4+t4.*t21.*t28.*t41.*6.0e-4-(t4.*t28.*t29.*t40)./1.0e+4-t4.*t21.*t28.*t29.*t40.^2.*6.0e-4))+t60.*v11.*v22)-t60.*v11.*v21.*v32;-v31.*(v21.*(t59.*v13+v11.*((n.*t19)./4.096e+7+t5.*t20.*t38.*6.0e-5-t5.*t26.*t37.*3.0e-5+t5.*t17.*t20.*t38.*6.0e-5-(t5.*t17.*t26.*t37)./1.0e+5-t5.*t17.*t20.*t26.*t37.^2.*6.0e-5))+t59.*v11.*v23)-t59.*v11.*v21.*v33;-v31.*(v21.*(t58.*v14+v11.*(t15.*(h-1.0).*8.75e-7+h.*t22.*t34.*6.0e-4-(h.*t27.*t33)./1.0e+4-h.*t22.*t27.*t33.^2.*6.0e-4))+t58.*v11.*v24)-t58.*v11.*v21.*v34];

function J3 = J3(in1,in2,in3,in4,in5)
%J3
%    J3 = J3(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:27:43

J3 = [0.0;0.0;0.0;0.0];

function B1 = B1(in1,in2,in3,in4,in5)
%B1
%    B1 = B1(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:27:43

n = in1(:,3);
p11 = in5(1,:);
v13 = in3(3,:);
v23 = in4(3,:);
B1 = [n.^2.*p11.*v13.*v23.*4.32e+2;0.0;0.0;0.0];

function A2 = A2(in1,in2,in3,in4,in5)
%A2
%    A2 = A2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:27:43

A2 = [0.0;0.0;0.0;0.0];

