function F = Morris_Lecar_multilinearforms
F.A = @A;
F.J1 = @J1;
F.B = @B;
F.A1 = @A1;
F.J2 = @J2;
F.C = @C;
F.J3 = @J3;
F.B1 = @B1;
F.A2 = @A2;

function A = A(in1,in2)
%A
%    A = A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:40:43

V = in1(:,1);
v3 = in2(:,2);
w = in1(:,2);
t2 = V./1.8e+1;
t3 = V./3.0e+1;
t4 = V./6.0e+1;
t5 = v3./3.0e+1;
t6 = v3./6.0e+1;
t7 = -t5;
t8 = -t6;
t9 = t2+1.0./1.5e+1;
t10 = tanh(t9);
t11 = t3+t7;
t12 = t4+t8;
t13 = cosh(t12);
t14 = tanh(t11);
A = reshape([t10.*(-1.1e+1./1.0e+2)-w.*(2.0./5.0)+((t10.^2.*(1.1e+1./9.0e+1)-1.1e+1./9.0e+1).*(V-1.2e+2))./2.0e+1-2.1e+1./1.0e+2,(sinh(t12).*(t14./2.0-w+1.0./2.0))./1.5e+3-(t13.*(t14.^2./6.0e+1-1.0./6.0e+1))./2.5e+1,V.*(-2.0./5.0)-1.68e+2./5.0,t13.*(-1.0./2.5e+1)],[2,2]);

function J1 = J1(in1,in2)
%J1
%    J1 = J1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:40:43

V = in1(:,1);
v3 = in2(:,2);
w = in1(:,2);
t2 = V./3.0e+1;
t3 = V./6.0e+1;
t4 = v3./3.0e+1;
t5 = v3./6.0e+1;
t6 = -t4;
t7 = -t5;
t8 = t2+t6;
t9 = t3+t7;
t10 = tanh(t8);
J1 = reshape([1.0./2.0e+1,0.0,0.0,sinh(t9).*(t10./2.0-w+1.0./2.0).*(-6.666666666666667e-4)+(cosh(t9).*(t10.^2./6.0e+1-1.0./6.0e+1))./2.5e+1],[2,2]);

function B = B(in1,in2,in3,in4)
%B
%    B = B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:40:43

V = in1(:,1);
v3 = in2(:,2);
v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
w = in1(:,2);
t2 = V./1.8e+1;
t3 = V./3.0e+1;
t4 = V./6.0e+1;
t5 = v3./3.0e+1;
t6 = v3./6.0e+1;
t7 = -t5;
t8 = -t6;
t9 = t2+1.0./1.5e+1;
t10 = tanh(t9);
t12 = t3+t7;
t13 = t4+t8;
t11 = t10.^2;
t14 = cosh(t13);
t15 = sinh(t13);
t16 = tanh(t12);
t17 = t16.^2;
B = [v11.*v22.*(-2.0./5.0)-v21.*(v12.*(2.0./5.0)+v11.*(t11.*(-1.1e+1./9.0e+2)+t10.*(t11./1.8e+1-1.0./1.8e+1).*(V-1.2e+2).*(1.1e+1./9.0e+2)+1.1e+1./9.0e+2));-v21.*((t15.*v12)./1.5e+3-v11.*(t15.*(t17./6.0e+1-1.0./6.0e+1).*(-1.0./7.5e+2)+(t14.*(t16./2.0-w+1.0./2.0))./9.0e+4+(t14.*t16.*(t17./3.0e+1-1.0./3.0e+1))./7.5e+2))-(t15.*v11.*v22)./1.5e+3];

function J2 = J2(in1,in2,in3,in4)
%J2
%    J2 = J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:40:43

V = in1(:,1);
p12 = in3(2,:);
p22 = in4(2,:);
v3 = in2(:,2);
w = in1(:,2);
t2 = V./3.0e+1;
t3 = V./6.0e+1;
t4 = v3./3.0e+1;
t5 = v3./6.0e+1;
t6 = -t4;
t7 = -t5;
t8 = t2+t6;
t9 = t3+t7;
t10 = cosh(t9);
t11 = tanh(t8);
t12 = t11.^2;
J2 = [0.0;p12.*p22.*(sinh(t9).*(t12./6.0e+1-1.0./6.0e+1).*(-1.0./7.5e+2)+(t10.*(t11./2.0-w+1.0./2.0))./9.0e+4+(t10.*t11.*(t12./3.0e+1-1.0./3.0e+1))./7.5e+2)];

function A1 = A1(in1,in2,in3,in4)
%A1
%    A1 = A1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:40:43

V = in1(:,1);
p12 = in4(2,:);
v3 = in2(:,2);
v11 = in3(1,:);
v12 = in3(2,:);
w = in1(:,2);
t2 = V./3.0e+1;
t3 = V./6.0e+1;
t4 = v3./3.0e+1;
t5 = v3./6.0e+1;
t6 = -t4;
t7 = -t5;
t8 = t2+t6;
t9 = t3+t7;
t10 = cosh(t9);
t11 = sinh(t9);
t12 = tanh(t8);
t13 = t12.^2;
A1 = [0.0;p12.*((t11.*v12)./1.5e+3-v11.*(t11.*(t13./6.0e+1-1.0./6.0e+1).*(-1.0./7.5e+2)+(t10.*(t12./2.0-w+1.0./2.0))./9.0e+4+(t10.*t12.*(t13./3.0e+1-1.0./3.0e+1))./7.5e+2))];

function C = C(in1,in2,in3,in4,in5)
%C
%    C = C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:40:43

V = in1(:,1);
v3 = in2(:,2);
v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
v31 = in5(1,:);
v32 = in5(2,:);
w = in1(:,2);
t2 = V./1.8e+1;
t3 = V./3.0e+1;
t4 = V./6.0e+1;
t5 = V-1.2e+2;
t6 = v3./3.0e+1;
t7 = v3./6.0e+1;
t8 = -t6;
t9 = -t7;
t10 = t2+1.0./1.5e+1;
t11 = tanh(t10);
t13 = t3+t8;
t14 = t4+t9;
t12 = t11.^2;
t15 = cosh(t14);
t16 = sinh(t14);
t17 = tanh(t13);
t18 = t17.^2;
t19 = t12./1.8e+1;
t20 = t18./3.0e+1;
t21 = t19-1.0./1.8e+1;
t22 = t20-1.0./3.0e+1;
C = [v11.*v21.*v31.*(t11.*t21.*(-1.1e+1./3.0e+2)+t5.*t21.^2.*(1.1e+1./9.0e+2)+t5.*t12.*t21.*1.358024691358025e-3);-v31.*(v21.*(v11.*((t15.*(t18./6.0e+1-1.0./6.0e+1))./3.0e+4+(t15.*t22.^2)./7.5e+2-(t16.*(t17./2.0-w+1.0./2.0))./5.4e+6+(t15.*t18.*t22)./1.125e+4-(t16.*t17.*t22)./1.5e+4)+(t15.*v12)./9.0e+4)+(t15.*v11.*v22)./9.0e+4)-(t15.*v11.*v21.*v32)./9.0e+4];

function J3 = J3(in1,in2,in3,in4,in5)
%J3
%    J3 = J3(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:40:43

V = in1(:,1);
p12 = in3(2,:);
p22 = in4(2,:);
p32 = in5(2,:);
v3 = in2(:,2);
w = in1(:,2);
t2 = V./3.0e+1;
t3 = V./6.0e+1;
t4 = v3./3.0e+1;
t5 = v3./6.0e+1;
t6 = -t4;
t7 = -t5;
t8 = t2+t6;
t9 = t3+t7;
t10 = cosh(t9);
t11 = sinh(t9);
t12 = tanh(t8);
t13 = t12.^2;
t14 = t13./3.0e+1;
t15 = t14-1.0./3.0e+1;
J3 = [0.0;p12.*p22.*p32.*((t10.*(t13./6.0e+1-1.0./6.0e+1))./3.0e+4+(t10.*t15.^2)./7.5e+2-(t11.*(t12./2.0-w+1.0./2.0))./5.4e+6+(t10.*t13.*t15)./1.125e+4-(t11.*t12.*t15)./1.5e+4)];

function B1 = B1(in1,in2,in3,in4,in5)
%B1
%    B1 = B1(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:40:44

V = in1(:,1);
p12 = in5(2,:);
v3 = in2(:,2);
v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
w = in1(:,2);
t2 = V./3.0e+1;
t3 = V./6.0e+1;
t4 = v3./3.0e+1;
t5 = v3./6.0e+1;
t6 = -t4;
t7 = -t5;
t8 = t2+t6;
t9 = t3+t7;
t10 = cosh(t9);
t11 = sinh(t9);
t12 = tanh(t8);
t13 = t12.^2;
t14 = t13./3.0e+1;
t15 = t14-1.0./3.0e+1;
B1 = [0.0;p12.*(v21.*(v11.*((t10.*(t13./6.0e+1-1.0./6.0e+1))./3.0e+4+(t10.*t15.^2)./7.5e+2-(t11.*(t12./2.0-w+1.0./2.0))./5.4e+6+(t10.*t13.*t15)./1.125e+4-(t11.*t12.*t15)./1.5e+4)+(t10.*v12)./9.0e+4)+(t10.*v11.*v22)./9.0e+4)];

function A2 = A2(in1,in2,in3,in4,in5)
%A2
%    A2 = A2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:40:44

V = in1(:,1);
p12 = in4(2,:);
p22 = in5(2,:);
v3 = in2(:,2);
v11 = in3(1,:);
v12 = in3(2,:);
w = in1(:,2);
t2 = V./3.0e+1;
t3 = V./6.0e+1;
t4 = v3./3.0e+1;
t5 = v3./6.0e+1;
t6 = -t4;
t7 = -t5;
t8 = t2+t6;
t9 = t3+t7;
t10 = cosh(t9);
t11 = sinh(t9);
t12 = tanh(t8);
t13 = t12.^2;
t14 = t13./3.0e+1;
t15 = t14-1.0./3.0e+1;
A2 = [0.0;-p12.*p22.*(v11.*((t10.*(t13./6.0e+1-1.0./6.0e+1))./3.0e+4+(t10.*t15.^2)./7.5e+2-(t11.*(t12./2.0-w+1.0./2.0))./5.4e+6+(t10.*t13.*t15)./1.125e+4-(t11.*t12.*t15)./1.5e+4)+(t10.*v12)./9.0e+4)];

