function F = PredatorPrey_multilinearforms
F.A = @A;
F.J1 = @J1;
F.B = @B;
F.A1 = @A1;
F.J2 = @J2;
F.C = @C;
F.J3 = @J3;
F.B1 = @B1;
F.A2 = @A2;

function A = A(in1,in2)
%A
%    A = A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:43:33

d = in2(:,1);
x = in1(:,1);
y = in1(:,2);
t2 = x+1.0;
t3 = 1.0./t2;
t4 = t3.^2;
t5 = t3.*x;
A = reshape([-x-t3.*y+t4.*x.*y+1.0,y.*(t3-t4.*x),-t5,-d+t5],[2,2]);

function J1 = J1(in1,in2)
%J1
%    J1 = J1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:43:33

y = in1(:,2);
J1 = reshape([0.0,-y,0.0,-1.0],[2,2]);

function B = B(in1,in2,in3,in4)
%B
%    B = B(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:43:33

v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
x = in1(:,1);
y = in1(:,2);
t2 = x+1.0;
t3 = 1.0./t2;
t4 = t3.^2;
t5 = t3.^3;
t7 = -t3;
t6 = t4.*x;
t8 = t6+t7;
t9 = -v11.*v22.*(t3-t6);
B = [t9-v21.*(v11.*(t4.*y.*-2.0+t5.*x.*y.*2.0+1.0)+t3.*v12-t6.*v12);v21.*(v12.*(t3-t6)-v11.*y.*(t4.*2.0-t5.*x.*2.0))+v11.*v22.*(t3-t6)];

function J2 = J2(in1,in2,in3,in4)
%J2
%    J2 = J2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:43:33

J2 = [0.0;0.0];

function A1 = A1(in1,in2,in3,in4)
%A1
%    A1 = A1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:43:33

p11 = in4(1,:);
v12 = in3(2,:);
A1 = [0.0;-p11.*v12];

function C = C(in1,in2,in3,in4,in5)
%C
%    C = C(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:43:33

v11 = in3(1,:);
v12 = in3(2,:);
v21 = in4(1,:);
v22 = in4(2,:);
v31 = in5(1,:);
v32 = in5(2,:);
x = in1(:,1);
y = in1(:,2);
t2 = x+1.0;
t3 = 1.0./t2.^2;
t4 = 1.0./t2.^3;
t5 = t3.^2;
t6 = t3.*2.0;
t7 = t4.*x.*2.0;
t8 = -t6;
t10 = -v11.*v22.*(t6-t7);
t11 = -v11.*v21.*v32.*(t6-t7);
t9 = t7+t8;
C = [-v31.*(t10+v21.*(v11.*(t4.*y.*6.0-t5.*x.*y.*6.0)-t3.*v12.*2.0+t7.*v12))+v11.*v21.*v32.*(t6-t7);t11-v31.*(v21.*(v12.*(t6-t7)-v11.*y.*(t4.*6.0-t5.*x.*6.0))+v11.*v22.*(t6-t7))];

function J3 = J3(in1,in2,in3,in4,in5)
%J3
%    J3 = J3(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:43:33

J3 = [0.0;0.0];

function B1 = B1(in1,in2,in3,in4,in5)
%B1
%    B1 = B1(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:43:33

B1 = [0.0;0.0];

function A2 = A2(in1,in2,in3,in4,in5)
%A2
%    A2 = A2(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Sep-2021 23:43:33

A2 = [0.0;0.0];

